### ISSUE TITLE
RFC consider moving to jazzband/pycqa etc

### ISSUE THREAD

**Issue by graingert** [PyCQA/python-modernize#213]
> I'm also happy in principle to turn it over to PyCQA, but I'd want the other current maintainers to agree on a move like that. And presumably it also depends on whether the people in PyCQA consider this in scope.

_Originally posted by @takluyver in https://github.com/python-modernize/python-modernize/pull/203#issuecomment-660692865_

**Comment by graingert** [comment]
@daira ^

**Comment by takluyver** [comment]
Thanks @graingert for organising the move. :-)
